version: '3.8'

services:
  backend:
    image: "${BACKEND_IMAGE_NAME}"
    environment:
      - ENVIRONMENT=prod
    env_file:
      - .env.prod
    ports: []

  frontend:
    image: "${FRONTEND_IMAGE_NAME}"
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env.prod
    ports:
      - "80:80"

  db:
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: